### ISSUE TITLE
Java11+工具窗口显示不完整

### ISSUE THREAD

**Issue by 0xtlu** [HotBoy-java/PotatoTool#10]
java11 -jar PotatoTool.jar 运行后无法看到完整工具界面，屏幕分辨率为1160*642。
![image](https://github.com/HotBoy-java/PotatoTool/assets/79645308/854010ee-ec47-49af-baf8-748edab43f52)

应该是屏幕比较垃圾，修改分辨率为1600*1200后重新运行可显示完整，但系统会出现滚动条导致操作麻烦。
![image](https://github.com/HotBoy-java/PotatoTool/assets/79645308/ff824097-2ed0-4e80-8ff1-fa9174f65ba8)

还发现，运行是会出现告警，我不确定是否和它有关：
$ java11 -jar PotatoTool.jar
x月 xx, 2024 xxx 下午 com.sun.javafx.application.PlatformImpl startup
警告: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @50b9b473'

经过引入javafx-sdk-11后，不在出现如上告警，但窗口无法完全显示
java11 --module-path ..\jdk-11\javafx-sdk-11\lib --add-modules javafx.controls,javafx.fxml -jar PotatoTool.jar

**Comment by ljy1058318852** [comment]
告警是因为非模块化，可忽略。已内置javafx，无需手动添加（除非是mac的M系列，下个版本1.2已兼容）。

屏幕尺寸兼容也将在下个版本1.2完善
