### ISSUE TITLE
突然乱码了，一开始是没有的

### ISSUE THREAD

**Issue by LwkFresh** [HotBoy-java/PotatoTool#12]
![image](https://github.com/user-attachments/assets/22605eb8-1695-4e2e-81c7-042dbb92b743)

**Comment by ljy1058318852** [comment]
目前已知：使用过1.0内测版的电脑会出现这个bug（如果没有使用过测试版本，暂未知其他原因，如可复现劳烦告知）

解决方案：请进入这个目录 %USERPROFILE%.PotatoTool，删除掉config.json，重新打开本工具即可恢复

**Comment by LwkFresh** [comment]
没使用过测试版本，暂无法复现，感谢您的解决方案

**Comment by ljy1058318852** [comment]
> 没使用过测试版本，暂无法复现，感谢您的解决方案

随时等待您的补充，Thanks

**Comment by Neojacka** [comment]
是.potatocol目录下的config.json文件里面出现乱码，ascii不支持中文
