### ISSUE TITLE
界面

### ISSUE THREAD

**Issue by daichuan1** [HotBoy-java/PotatoTool#15]
界面能优化下吗，来回切换时容易卡

**Comment by Minemetero** [comment]
提一嘴，能不能开源啊

**Comment by ljy1058318852** [comment]
> 提一嘴，能不能开源啊

目前确实有将其开源的想法，不过还处于规划和筹备阶段，有许多细节需要进一步梳理和完善，比如代码的优化、文档的补充以及确保开源后的维护和支持体系能够稳定运行等。所以暂时还无法确定具体的开源时间。

**Comment by ljy1058318852** [comment]
> 界面能优化下吗，来回切换时容易卡

V2.1已优化，下午更新github
