### ISSUE TITLE
[建议] webshell交互流量解密完毕后给出明显webshell交互类型提示

### ISSUE THREAD

**Issue by Superhero-zero** [HotBoy-java/PotatoTool#6]
当工具成功解密出原始数据后，希望能有一个明显的提示说是属于什么类型的webshell流量
![image](https://github.com/HotBoy-java/PotatoTool/assets/66772820/c4adae9b-6d1e-4e41-9c0d-8382b76878b0)

**Comment by ljy1058318852** [comment]
很好的建议，将在下个版本中，针对于明确的webshell流量提示类型
