### ISSUE TITLE
程序卡死

### ISSUE THREAD

**Issue by hughink** [HotBoy-java/PotatoTool#8]
在一键解密位置输入md5 值程序卡死

**Comment by ljy1058318852** [comment]
md5后台500w字典多线程爆破中，比较慢，且线程与ui未分离，导致视觉上卡死。  md5下个版本将存储数据库优化解密方案，线程分离，线程数可控，以此避免卡死感

**Comment by ljy1058318852** [comment]
md5后台500w字典多线程爆破中，比较慢，且线程与ui未分离，导致视觉上卡死。 md5下个版本将存储数据库优化解密方案，线程分离，线程数可控，以此避免卡死感
