### ISSUE TITLE
字体不正常

### ISSUE THREAD

**Issue by csxxy** [HotBoy-java/PotatoTool#9]
![图片](https://github.com/HotBoy-java/PotatoTool/assets/104177738/a2e5788e-fbb6-4638-9f5b-add5f9652ec0)

**Comment by ljy1058318852** [comment]
临时尝试修改桌面分辨率，下个版本将优化显示。方便话我们交流群里沟通一下，以便于下次优化后测试

**Comment by ljy1058318852** [comment]
请问最新版是否还会出现相同问题
